services:
  web:
    container_name: file-axonivy-works-web
    build: ./docker/apache
    volumes:
      - ./:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 8080:80
